#!/sbin/busybox sh
echo Starting..
# initramfs pre-boot init script

echo Mounting...
# Mount the /proc and /sys filesystems
mount -t proc none /proc
mount -t sysfs none /sys
mount -t tmpfs none /dev

# Something (what?) needs a few cycles here
sleep 1

# Suppressing some annoying messages
echo 0 >/proc/sys/kernel/hung_task_timeout_secs 

echo Creating devices
# Populate /dev
mdev -s

echo Installing...
time sh /installer.sh

echo "Switching to console. Press <Ctrl+D> to reboot"
sh -i </dev/console >/dev/console 2>&1

# Clean up
umount /proc
umount /sys
umount /dev

# Rebooting
echo Rebooting...
sleep 1
reboot -f